export const CURRENT_LOCATION_REQUEST = "CURRENT_LOCATION_REQUEST";
export const CURRENT_LOCATION_SUCCESS = " CURRENT_LOCATION_SUCCESS";
export const CURRENT_LOCATION_FAIL = " CURRENT_LOCATION_FAIL";
