const StorageUnitData = [
  {
    id: 2,
    per_unit_price: 7.0,
    storage_provider: {
      id: 1,
      name: "StephensonStorage",
      user: {
        email: "muhammadhasan8988@gmail.com",
        first_name: "",
        last_name: "",
      },
      phone_number: "+122039666",
      fax_number: "4144444",
      email: "admin@StephensonContainersandMore.com",
      website: "https://www.GoodmanRyderRentalTrucks.com",
      facebook: null,
      instagram: null,
      twitter: null,
      google_buisness: null,
    },
    location: {
      id: 2,
      address: "New York, NY, United States of America",
      city: "New York",
      country: "United States",
      country_code: "us",
      county: null,
      postcode: 0,
      district: null,
      lat: 40.7127281,
      lon: -74.0060152,
    },
    total_size: 5600,
    free_space: 5600,
    total_rooms: 3,
    occupied_space: 0,
    total_size_field: "75 x 75",
    free_space_field: "75 x 75",
    occupied_space_field: "0 x 0",
    createdAt: new Date().toISOString(),
  },

  {
    id: 1,
    per_unit_price: 3.0,
    storage_provider: {
      id: 1,
      name: "StephensonStorage",
      user: {
        email: "muhammadhasan8988@gmail.com",
        first_name: "",
        last_name: "",
      },
      phone_number: "+122039666",
      fax_number: "4144444",
      email: "admin@StephensonContainersandMore.com",
      website: "https://www.GoodmanRyderRentalTrucks.com",
      facebook: null,
      instagram: null,
      twitter: null,
      google_buisness: null,
    },
    location: {
      id: 1,
      address: "California, United States of America",
      city: null,
      country: "United States",
      country_code: "us",
      county: null,
      postcode: 0,
      district: null,
      lat: 36.7014631,
      lon: -118.755997,
    },
    total_size: 3000,
    free_space: 3000,
    total_rooms: 3,
    occupied_space: 0,
    total_size_field: "55 x 55",
    free_space_field: "55 x 55",
    occupied_space_field: "0 x 0",
    createdAt: new Date().toISOString(),
  },
  {
    id: 3,
    per_unit_price: 5.0,
    storage_provider: {
      id: 1,
      name: "StephensonStorage",
      user: {
        email: "muhammadhasan8988@gmail.com",
        first_name: "",
        last_name: "",
      },
      phone_number: "+122039666",
      fax_number: "4144444",
      email: "admin@StephensonContainersandMore.com",
      website: "https://www.GoodmanRyderRentalTrucks.com",
      facebook: null,
      instagram: null,
      twitter: null,
      google_buisness: null,
    },
    location: {
      id: 3,
      address: "America, Ogoja, Nigeria",
      city: "America",
      country: "Nigeria",
      country_code: "ng",
      county: "Ogoja",
      postcode: 0,
      district: null,
      lat: 6.6223,
      lon: 8.8342,
    },
    total_size: 6000,
    free_space: 5000,
    total_rooms: 3,
    occupied_space: 1000,
    total_size_field: "77 x 77",
    free_space_field: "77 x 77",
    occupied_space_field: "0 x 0",
    createdAt: new Date().toISOString(),
  },
];

export default StorageUnitData;
